// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/AaronCheng1996/sendmemes-discord-bot/internal/entity"
	repo "github.com/AaronCheng1996/sendmemes-discord-bot/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), arg0)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(arg0 context.Context, arg1 entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), arg0, arg1)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockAlbumsRepo is a mock of AlbumsRepo interface.
type MockAlbumsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumsRepoMockRecorder
	isgomock struct{}
}

// MockAlbumsRepoMockRecorder is the mock recorder for MockAlbumsRepo.
type MockAlbumsRepoMockRecorder struct {
	mock *MockAlbumsRepo
}

// NewMockAlbumsRepo creates a new mock instance.
func NewMockAlbumsRepo(ctrl *gomock.Controller) *MockAlbumsRepo {
	mock := &MockAlbumsRepo{ctrl: ctrl}
	mock.recorder = &MockAlbumsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumsRepo) EXPECT() *MockAlbumsRepoMockRecorder {
	return m.recorder
}

// ClearCover mocks base method.
func (m *MockAlbumsRepo) ClearCover(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCover", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCover indicates an expected call of ClearCover.
func (mr *MockAlbumsRepoMockRecorder) ClearCover(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCover", reflect.TypeOf((*MockAlbumsRepo)(nil).ClearCover), ctx, albumID)
}

// Count mocks base method.
func (m *MockAlbumsRepo) Count(ctx context.Context, q repo.AlbumAdminListQuery) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, q)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAlbumsRepoMockRecorder) Count(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAlbumsRepo)(nil).Count), ctx, q)
}

// Create mocks base method.
func (m *MockAlbumsRepo) Create(ctx context.Context, name string, sendMode entity.AlbumSendMode, sendConfigJSON string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, sendMode, sendConfigJSON)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlbumsRepoMockRecorder) Create(ctx, name, sendMode, sendConfigJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlbumsRepo)(nil).Create), ctx, name, sendMode, sendConfigJSON)
}

// Delete mocks base method.
func (m *MockAlbumsRepo) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlbumsRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlbumsRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAlbumsRepo) GetByID(ctx context.Context, id int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAlbumsRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAlbumsRepo)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockAlbumsRepo) GetByName(ctx context.Context, name string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockAlbumsRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockAlbumsRepo)(nil).GetByName), ctx, name)
}

// GetOrCreate mocks base method.
func (m *MockAlbumsRepo) GetOrCreate(ctx context.Context, name string, defaultMode entity.AlbumSendMode) (entity.Album, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, name, defaultMode)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockAlbumsRepoMockRecorder) GetOrCreate(ctx, name, defaultMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockAlbumsRepo)(nil).GetOrCreate), ctx, name, defaultMode)
}

// GetRandom mocks base method.
func (m *MockAlbumsRepo) GetRandom(ctx context.Context) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom", ctx)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockAlbumsRepoMockRecorder) GetRandom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockAlbumsRepo)(nil).GetRandom), ctx)
}

// GetRandomExcludeRecent mocks base method.
func (m *MockAlbumsRepo) GetRandomExcludeRecent(ctx context.Context, excludeN int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomExcludeRecent", ctx, excludeN)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomExcludeRecent indicates an expected call of GetRandomExcludeRecent.
func (mr *MockAlbumsRepoMockRecorder) GetRandomExcludeRecent(ctx, excludeN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomExcludeRecent", reflect.TypeOf((*MockAlbumsRepo)(nil).GetRandomExcludeRecent), ctx, excludeN)
}

// IncrRating mocks base method.
func (m *MockAlbumsRepo) IncrRating(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrRating", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrRating indicates an expected call of IncrRating.
func (mr *MockAlbumsRepoMockRecorder) IncrRating(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrRating", reflect.TypeOf((*MockAlbumsRepo)(nil).IncrRating), ctx, albumID)
}

// List mocks base method.
func (m *MockAlbumsRepo) List(ctx context.Context, q repo.AlbumAdminListQuery, offset, limit int) ([]entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAlbumsRepoMockRecorder) List(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlbumsRepo)(nil).List), ctx, q, offset, limit)
}

// MarkSent mocks base method.
func (m *MockAlbumsRepo) MarkSent(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockAlbumsRepoMockRecorder) MarkSent(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockAlbumsRepo)(nil).MarkSent), ctx, albumID)
}

// SetCover mocks base method.
func (m *MockAlbumsRepo) SetCover(ctx context.Context, albumID, coverImageID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCover", ctx, albumID, coverImageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCover indicates an expected call of SetCover.
func (mr *MockAlbumsRepoMockRecorder) SetCover(ctx, albumID, coverImageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCover", reflect.TypeOf((*MockAlbumsRepo)(nil).SetCover), ctx, albumID, coverImageID)
}

// Update mocks base method.
func (m *MockAlbumsRepo) Update(ctx context.Context, id int, name string, sendMode entity.AlbumSendMode, sendConfigJSON string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, sendMode, sendConfigJSON)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlbumsRepoMockRecorder) Update(ctx, id, name, sendMode, sendConfigJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlbumsRepo)(nil).Update), ctx, id, name, sendMode, sendConfigJSON)
}

// MockImagesRepo is a mock of ImagesRepo interface.
type MockImagesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockImagesRepoMockRecorder
	isgomock struct{}
}

// MockImagesRepoMockRecorder is the mock recorder for MockImagesRepo.
type MockImagesRepoMockRecorder struct {
	mock *MockImagesRepo
}

// NewMockImagesRepo creates a new mock instance.
func NewMockImagesRepo(ctrl *gomock.Controller) *MockImagesRepo {
	mock := &MockImagesRepo{ctrl: ctrl}
	mock.recorder = &MockImagesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImagesRepo) EXPECT() *MockImagesRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockImagesRepo) Count(ctx context.Context, q repo.ImageAdminListQuery) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, q)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockImagesRepoMockRecorder) Count(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockImagesRepo)(nil).Count), ctx, q)
}

// Delete mocks base method.
func (m *MockImagesRepo) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockImagesRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImagesRepo)(nil).Delete), ctx, id)
}

// DeleteByAlbumNotInFileIDs mocks base method.
func (m *MockImagesRepo) DeleteByAlbumNotInFileIDs(ctx context.Context, albumID int, fileIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAlbumNotInFileIDs", ctx, albumID, fileIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAlbumNotInFileIDs indicates an expected call of DeleteByAlbumNotInFileIDs.
func (mr *MockImagesRepoMockRecorder) DeleteByAlbumNotInFileIDs(ctx, albumID, fileIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAlbumNotInFileIDs", reflect.TypeOf((*MockImagesRepo)(nil).DeleteByAlbumNotInFileIDs), ctx, albumID, fileIDs)
}

// FindCoverByAlbum mocks base method.
func (m *MockImagesRepo) FindCoverByAlbum(ctx context.Context, albumID int) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCoverByAlbum", ctx, albumID)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindCoverByAlbum indicates an expected call of FindCoverByAlbum.
func (mr *MockImagesRepoMockRecorder) FindCoverByAlbum(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCoverByAlbum", reflect.TypeOf((*MockImagesRepo)(nil).FindCoverByAlbum), ctx, albumID)
}

// GetAllByAlbum mocks base method.
func (m *MockImagesRepo) GetAllByAlbum(ctx context.Context, albumID, excludeID int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByAlbum", ctx, albumID, excludeID)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByAlbum indicates an expected call of GetAllByAlbum.
func (mr *MockImagesRepoMockRecorder) GetAllByAlbum(ctx, albumID, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByAlbum", reflect.TypeOf((*MockImagesRepo)(nil).GetAllByAlbum), ctx, albumID, excludeID)
}

// GetByID mocks base method.
func (m *MockImagesRepo) GetByID(ctx context.Context, id int) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockImagesRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockImagesRepo)(nil).GetByID), ctx, id)
}

// GetDefault mocks base method.
func (m *MockImagesRepo) GetDefault(ctx context.Context) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefault", ctx)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefault indicates an expected call of GetDefault.
func (mr *MockImagesRepoMockRecorder) GetDefault(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefault", reflect.TypeOf((*MockImagesRepo)(nil).GetDefault), ctx)
}

// GetFirstByAlbum mocks base method.
func (m *MockImagesRepo) GetFirstByAlbum(ctx context.Context, albumID int) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstByAlbum", ctx, albumID)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFirstByAlbum indicates an expected call of GetFirstByAlbum.
func (mr *MockImagesRepoMockRecorder) GetFirstByAlbum(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstByAlbum", reflect.TypeOf((*MockImagesRepo)(nil).GetFirstByAlbum), ctx, albumID)
}

// GetRandom mocks base method.
func (m *MockImagesRepo) GetRandom(ctx context.Context) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom", ctx)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockImagesRepoMockRecorder) GetRandom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockImagesRepo)(nil).GetRandom), ctx)
}

// GetRandomByAlbum mocks base method.
func (m *MockImagesRepo) GetRandomByAlbum(ctx context.Context, albumID, limit, excludeID int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomByAlbum", ctx, albumID, limit, excludeID)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomByAlbum indicates an expected call of GetRandomByAlbum.
func (mr *MockImagesRepoMockRecorder) GetRandomByAlbum(ctx, albumID, limit, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomByAlbum", reflect.TypeOf((*MockImagesRepo)(nil).GetRandomByAlbum), ctx, albumID, limit, excludeID)
}

// GetRandomVideoByAlbum mocks base method.
func (m *MockImagesRepo) GetRandomVideoByAlbum(ctx context.Context, albumID int) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomVideoByAlbum", ctx, albumID)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRandomVideoByAlbum indicates an expected call of GetRandomVideoByAlbum.
func (mr *MockImagesRepoMockRecorder) GetRandomVideoByAlbum(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomVideoByAlbum", reflect.TypeOf((*MockImagesRepo)(nil).GetRandomVideoByAlbum), ctx, albumID)
}

// Insert mocks base method.
func (m *MockImagesRepo) Insert(ctx context.Context, img entity.Image) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, img)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockImagesRepoMockRecorder) Insert(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockImagesRepo)(nil).Insert), ctx, img)
}

// List mocks base method.
func (m *MockImagesRepo) List(ctx context.Context, q repo.ImageAdminListQuery, offset, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockImagesRepoMockRecorder) List(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockImagesRepo)(nil).List), ctx, q, offset, limit)
}

// SetPublicLink mocks base method.
func (m *MockImagesRepo) SetPublicLink(ctx context.Context, id int, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublicLink", ctx, id, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublicLink indicates an expected call of SetPublicLink.
func (mr *MockImagesRepoMockRecorder) SetPublicLink(ctx, id, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublicLink", reflect.TypeOf((*MockImagesRepo)(nil).SetPublicLink), ctx, id, link)
}

// Update mocks base method.
func (m *MockImagesRepo) Update(ctx context.Context, img entity.Image) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, img)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockImagesRepoMockRecorder) Update(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockImagesRepo)(nil).Update), ctx, img)
}

// UpsertByFileID mocks base method.
func (m *MockImagesRepo) UpsertByFileID(ctx context.Context, img entity.Image) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByFileID", ctx, img)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertByFileID indicates an expected call of UpsertByFileID.
func (mr *MockImagesRepoMockRecorder) UpsertByFileID(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByFileID", reflect.TypeOf((*MockImagesRepo)(nil).UpsertByFileID), ctx, img)
}

// MockDeliveryRulesRepo is a mock of DeliveryRulesRepo interface.
type MockDeliveryRulesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRulesRepoMockRecorder
	isgomock struct{}
}

// MockDeliveryRulesRepoMockRecorder is the mock recorder for MockDeliveryRulesRepo.
type MockDeliveryRulesRepoMockRecorder struct {
	mock *MockDeliveryRulesRepo
}

// NewMockDeliveryRulesRepo creates a new mock instance.
func NewMockDeliveryRulesRepo(ctrl *gomock.Controller) *MockDeliveryRulesRepo {
	mock := &MockDeliveryRulesRepo{ctrl: ctrl}
	mock.recorder = &MockDeliveryRulesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRulesRepo) EXPECT() *MockDeliveryRulesRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockDeliveryRulesRepo) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockDeliveryRulesRepoMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockDeliveryRulesRepo) Create(ctx context.Context, rule entity.DeliveryRule) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeliveryRulesRepoMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockDeliveryRulesRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeliveryRulesRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDeliveryRulesRepo) GetByID(ctx context.Context, id int64) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeliveryRulesRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDeliveryRulesRepo) List(ctx context.Context) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDeliveryRulesRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).List), ctx)
}

// ListActiveByTrigger mocks base method.
func (m *MockDeliveryRulesRepo) ListActiveByTrigger(ctx context.Context, triggerType string) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByTrigger", ctx, triggerType)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByTrigger indicates an expected call of ListActiveByTrigger.
func (mr *MockDeliveryRulesRepoMockRecorder) ListActiveByTrigger(ctx, triggerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByTrigger", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).ListActiveByTrigger), ctx, triggerType)
}

// Update mocks base method.
func (m *MockDeliveryRulesRepo) Update(ctx context.Context, rule entity.DeliveryRule) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeliveryRulesRepoMockRecorder) Update(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeliveryRulesRepo)(nil).Update), ctx, rule)
}

// MockAppSettingsRepo is a mock of AppSettingsRepo interface.
type MockAppSettingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAppSettingsRepoMockRecorder
	isgomock struct{}
}

// MockAppSettingsRepoMockRecorder is the mock recorder for MockAppSettingsRepo.
type MockAppSettingsRepoMockRecorder struct {
	mock *MockAppSettingsRepo
}

// NewMockAppSettingsRepo creates a new mock instance.
func NewMockAppSettingsRepo(ctrl *gomock.Controller) *MockAppSettingsRepo {
	mock := &MockAppSettingsRepo{ctrl: ctrl}
	mock.recorder = &MockAppSettingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppSettingsRepo) EXPECT() *MockAppSettingsRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAppSettingsRepo) Get(ctx context.Context) (entity.AppSettings, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAppSettingsRepoMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppSettingsRepo)(nil).Get), ctx)
}

// Upsert mocks base method.
func (m *MockAppSettingsRepo) Upsert(ctx context.Context, s entity.AppSettings) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAppSettingsRepoMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAppSettingsRepo)(nil).Upsert), ctx, s)
}

// MockAdminAuditRepo is a mock of AdminAuditRepo interface.
type MockAdminAuditRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAdminAuditRepoMockRecorder
	isgomock struct{}
}

// MockAdminAuditRepoMockRecorder is the mock recorder for MockAdminAuditRepo.
type MockAdminAuditRepoMockRecorder struct {
	mock *MockAdminAuditRepo
}

// NewMockAdminAuditRepo creates a new mock instance.
func NewMockAdminAuditRepo(ctrl *gomock.Controller) *MockAdminAuditRepo {
	mock := &MockAdminAuditRepo{ctrl: ctrl}
	mock.recorder = &MockAdminAuditRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminAuditRepo) EXPECT() *MockAdminAuditRepoMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAdminAuditRepo) Insert(ctx context.Context, log entity.AdminAuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAdminAuditRepoMockRecorder) Insert(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAdminAuditRepo)(nil).Insert), ctx, log)
}

// MockSyncEventsRepo is a mock of SyncEventsRepo interface.
type MockSyncEventsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncEventsRepoMockRecorder
	isgomock struct{}
}

// MockSyncEventsRepoMockRecorder is the mock recorder for MockSyncEventsRepo.
type MockSyncEventsRepoMockRecorder struct {
	mock *MockSyncEventsRepo
}

// NewMockSyncEventsRepo creates a new mock instance.
func NewMockSyncEventsRepo(ctrl *gomock.Controller) *MockSyncEventsRepo {
	mock := &MockSyncEventsRepo{ctrl: ctrl}
	mock.recorder = &MockSyncEventsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncEventsRepo) EXPECT() *MockSyncEventsRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockSyncEventsRepo) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockSyncEventsRepoMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockSyncEventsRepo)(nil).Count), ctx)
}

// Insert mocks base method.
func (m *MockSyncEventsRepo) Insert(ctx context.Context, ev entity.SyncEvent) (entity.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, ev)
	ret0, _ := ret[0].(entity.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockSyncEventsRepoMockRecorder) Insert(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSyncEventsRepo)(nil).Insert), ctx, ev)
}

// List mocks base method.
func (m *MockSyncEventsRepo) List(ctx context.Context, offset, limit int) ([]entity.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]entity.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSyncEventsRepoMockRecorder) List(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSyncEventsRepo)(nil).List), ctx, offset, limit)
}

// MockSystemRepo is a mock of SystemRepo interface.
type MockSystemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSystemRepoMockRecorder
	isgomock struct{}
}

// MockSystemRepoMockRecorder is the mock recorder for MockSystemRepo.
type MockSystemRepoMockRecorder struct {
	mock *MockSystemRepo
}

// NewMockSystemRepo creates a new mock instance.
func NewMockSystemRepo(ctrl *gomock.Controller) *MockSystemRepo {
	mock := &MockSystemRepo{ctrl: ctrl}
	mock.recorder = &MockSystemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemRepo) EXPECT() *MockSystemRepoMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSystemRepo) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSystemRepoMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSystemRepo)(nil).Ping), ctx)
}

// MockPCloudAPI is a mock of PCloudAPI interface.
type MockPCloudAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPCloudAPIMockRecorder
	isgomock struct{}
}

// MockPCloudAPIMockRecorder is the mock recorder for MockPCloudAPI.
type MockPCloudAPIMockRecorder struct {
	mock *MockPCloudAPI
}

// NewMockPCloudAPI creates a new mock instance.
func NewMockPCloudAPI(ctrl *gomock.Controller) *MockPCloudAPI {
	mock := &MockPCloudAPI{ctrl: ctrl}
	mock.recorder = &MockPCloudAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPCloudAPI) EXPECT() *MockPCloudAPIMockRecorder {
	return m.recorder
}

// GetFileLink mocks base method.
func (m *MockPCloudAPI) GetFileLink(ctx context.Context, fileID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileLink", ctx, fileID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileLink indicates an expected call of GetFileLink.
func (mr *MockPCloudAPIMockRecorder) GetFileLink(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileLink", reflect.TypeOf((*MockPCloudAPI)(nil).GetFileLink), ctx, fileID)
}

// GetFilePublicLink mocks base method.
func (m *MockPCloudAPI) GetFilePublicLink(ctx context.Context, fileID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePublicLink", ctx, fileID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePublicLink indicates an expected call of GetFilePublicLink.
func (mr *MockPCloudAPIMockRecorder) GetFilePublicLink(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePublicLink", reflect.TypeOf((*MockPCloudAPI)(nil).GetFilePublicLink), ctx, fileID)
}

// ListFolder mocks base method.
func (m *MockPCloudAPI) ListFolder(ctx context.Context, folderID int64) ([]repo.PCloudEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolder", ctx, folderID)
	ret0, _ := ret[0].([]repo.PCloudEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFolder indicates an expected call of ListFolder.
func (mr *MockPCloudAPIMockRecorder) ListFolder(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolder", reflect.TypeOf((*MockPCloudAPI)(nil).ListFolder), ctx, folderID)
}

// PublicThumbURL mocks base method.
func (m *MockPCloudAPI) PublicThumbURL(publicLink string, fileID int64, size string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicThumbURL", publicLink, fileID, size)
	ret0, _ := ret[0].(string)
	return ret0
}

// PublicThumbURL indicates an expected call of PublicThumbURL.
func (mr *MockPCloudAPIMockRecorder) PublicThumbURL(publicLink, fileID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicThumbURL", reflect.TypeOf((*MockPCloudAPI)(nil).PublicThumbURL), publicLink, fileID, size)
}
