// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/contracts.go -destination=internal/usecase/mocks_usecase_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/AaronCheng1996/sendmemes-discord-bot/internal/entity"
	repo "github.com/AaronCheng1996/sendmemes-discord-bot/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockImages is a mock of Images interface.
type MockImages struct {
	ctrl     *gomock.Controller
	recorder *MockImagesMockRecorder
	isgomock struct{}
}

// MockImagesMockRecorder is the mock recorder for MockImages.
type MockImagesMockRecorder struct {
	mock *MockImages
}

// NewMockImages creates a new mock instance.
func NewMockImages(ctrl *gomock.Controller) *MockImages {
	mock := &MockImages{ctrl: ctrl}
	mock.recorder = &MockImagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImages) EXPECT() *MockImagesMockRecorder {
	return m.recorder
}

// CountAlbumMedia mocks base method.
func (m *MockImages) CountAlbumMedia(ctx context.Context, albumID int) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAlbumMedia", ctx, albumID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountAlbumMedia indicates an expected call of CountAlbumMedia.
func (mr *MockImagesMockRecorder) CountAlbumMedia(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAlbumMedia", reflect.TypeOf((*MockImages)(nil).CountAlbumMedia), ctx, albumID)
}

// GetAlbumBatch mocks base method.
func (m *MockImages) GetAlbumBatch(ctx context.Context, album entity.Album, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumBatch", ctx, album, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumBatch indicates an expected call of GetAlbumBatch.
func (mr *MockImagesMockRecorder) GetAlbumBatch(ctx, album, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumBatch", reflect.TypeOf((*MockImages)(nil).GetAlbumBatch), ctx, album, limit)
}

// GetAlbumByID mocks base method.
func (m *MockImages) GetAlbumByID(ctx context.Context, id int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumByID", ctx, id)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByID indicates an expected call of GetAlbumByID.
func (mr *MockImagesMockRecorder) GetAlbumByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByID", reflect.TypeOf((*MockImages)(nil).GetAlbumByID), ctx, id)
}

// GetAlbumCover mocks base method.
func (m *MockImages) GetAlbumCover(ctx context.Context, albumName string) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumCover", ctx, albumName)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAlbumCover indicates an expected call of GetAlbumCover.
func (mr *MockImagesMockRecorder) GetAlbumCover(ctx, albumName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumCover", reflect.TypeOf((*MockImages)(nil).GetAlbumCover), ctx, albumName)
}

// GetAlbumImages mocks base method.
func (m *MockImages) GetAlbumImages(ctx context.Context, albumName string, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumImages", ctx, albumName, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumImages indicates an expected call of GetAlbumImages.
func (mr *MockImagesMockRecorder) GetAlbumImages(ctx, albumName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumImages", reflect.TypeOf((*MockImages)(nil).GetAlbumImages), ctx, albumName, limit)
}

// GetComicPages mocks base method.
func (m *MockImages) GetComicPages(ctx context.Context, album entity.Album) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicPages", ctx, album)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicPages indicates an expected call of GetComicPages.
func (mr *MockImagesMockRecorder) GetComicPages(ctx, album any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicPages", reflect.TypeOf((*MockImages)(nil).GetComicPages), ctx, album)
}

// GetFullAlbum mocks base method.
func (m *MockImages) GetFullAlbum(ctx context.Context, albumName string) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullAlbum", ctx, albumName)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullAlbum indicates an expected call of GetFullAlbum.
func (mr *MockImagesMockRecorder) GetFullAlbum(ctx, albumName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullAlbum", reflect.TypeOf((*MockImages)(nil).GetFullAlbum), ctx, albumName)
}

// GetImage mocks base method.
func (m *MockImages) GetImage(ctx context.Context) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockImagesMockRecorder) GetImage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockImages)(nil).GetImage), ctx)
}

// GetRandom mocks base method.
func (m *MockImages) GetRandom(ctx context.Context) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom", ctx)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockImagesMockRecorder) GetRandom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockImages)(nil).GetRandom), ctx)
}

// GetRandomAlbumImages mocks base method.
func (m *MockImages) GetRandomAlbumImages(ctx context.Context, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomAlbumImages", ctx, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomAlbumImages indicates an expected call of GetRandomAlbumImages.
func (mr *MockImagesMockRecorder) GetRandomAlbumImages(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomAlbumImages", reflect.TypeOf((*MockImages)(nil).GetRandomAlbumImages), ctx, limit)
}

// GetRandomFromAlbum mocks base method.
func (m *MockImages) GetRandomFromAlbum(ctx context.Context, albumID, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomFromAlbum", ctx, albumID, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomFromAlbum indicates an expected call of GetRandomFromAlbum.
func (mr *MockImagesMockRecorder) GetRandomFromAlbum(ctx, albumID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomFromAlbum", reflect.TypeOf((*MockImages)(nil).GetRandomFromAlbum), ctx, albumID, limit)
}

// GetRandomVideo mocks base method.
func (m *MockImages) GetRandomVideo(ctx context.Context, albumID int) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomVideo", ctx, albumID)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRandomVideo indicates an expected call of GetRandomVideo.
func (mr *MockImagesMockRecorder) GetRandomVideo(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomVideo", reflect.TypeOf((*MockImages)(nil).GetRandomVideo), ctx, albumID)
}

// GetScheduledAlbum mocks base method.
func (m *MockImages) GetScheduledAlbum(ctx context.Context, excludeN int, filter entity.AlbumPathFilter) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledAlbum", ctx, excludeN, filter)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledAlbum indicates an expected call of GetScheduledAlbum.
func (mr *MockImagesMockRecorder) GetScheduledAlbum(ctx, excludeN, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledAlbum", reflect.TypeOf((*MockImages)(nil).GetScheduledAlbum), ctx, excludeN, filter)
}

// IncrAlbumRating mocks base method.
func (m *MockImages) IncrAlbumRating(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrAlbumRating", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrAlbumRating indicates an expected call of IncrAlbumRating.
func (mr *MockImagesMockRecorder) IncrAlbumRating(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrAlbumRating", reflect.TypeOf((*MockImages)(nil).IncrAlbumRating), ctx, albumID)
}

// MarkAlbumSent mocks base method.
func (m *MockImages) MarkAlbumSent(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAlbumSent", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAlbumSent indicates an expected call of MarkAlbumSent.
func (mr *MockImagesMockRecorder) MarkAlbumSent(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAlbumSent", reflect.TypeOf((*MockImages)(nil).MarkAlbumSent), ctx, albumID)
}

// ResolvePreviewURL mocks base method.
func (m *MockImages) ResolvePreviewURL(ctx context.Context, img entity.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePreviewURL", ctx, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePreviewURL indicates an expected call of ResolvePreviewURL.
func (mr *MockImagesMockRecorder) ResolvePreviewURL(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePreviewURL", reflect.TypeOf((*MockImages)(nil).ResolvePreviewURL), ctx, img)
}

// ResolvePublicURL mocks base method.
func (m *MockImages) ResolvePublicURL(ctx context.Context, img entity.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePublicURL", ctx, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePublicURL indicates an expected call of ResolvePublicURL.
func (mr *MockImagesMockRecorder) ResolvePublicURL(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePublicURL", reflect.TypeOf((*MockImages)(nil).ResolvePublicURL), ctx, img)
}

// ResolveURL mocks base method.
func (m *MockImages) ResolveURL(ctx context.Context, img entity.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveURL", ctx, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveURL indicates an expected call of ResolveURL.
func (mr *MockImagesMockRecorder) ResolveURL(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveURL", reflect.TypeOf((*MockImages)(nil).ResolveURL), ctx, img)
}

// SetAlbumMode mocks base method.
func (m *MockImages) SetAlbumMode(ctx context.Context, albumName string, mode entity.AlbumSendMode) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAlbumMode", ctx, albumName, mode)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAlbumMode indicates an expected call of SetAlbumMode.
func (mr *MockImagesMockRecorder) SetAlbumMode(ctx, albumName, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAlbumMode", reflect.TypeOf((*MockImages)(nil).SetAlbumMode), ctx, albumName, mode)
}

// TopRated mocks base method.
func (m *MockImages) TopRated(ctx context.Context, limit int) ([]entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopRated", ctx, limit)
	ret0, _ := ret[0].([]entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopRated indicates an expected call of TopRated.
func (mr *MockImagesMockRecorder) TopRated(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopRated", reflect.TypeOf((*MockImages)(nil).TopRated), ctx, limit)
}

// MockSync is a mock of Sync interface.
type MockSync struct {
	ctrl     *gomock.Controller
	recorder *MockSyncMockRecorder
	isgomock struct{}
}

// MockSyncMockRecorder is the mock recorder for MockSync.
type MockSyncMockRecorder struct {
	mock *MockSync
}

// NewMockSync creates a new mock instance.
func NewMockSync(ctrl *gomock.Controller) *MockSync {
	mock := &MockSync{ctrl: ctrl}
	mock.recorder = &MockSyncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSync) EXPECT() *MockSyncMockRecorder {
	return m.recorder
}

// SyncImages mocks base method.
func (m *MockSync) SyncImages(ctx context.Context) (entity.SyncReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncImages", ctx)
	ret0, _ := ret[0].(entity.SyncReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncImages indicates an expected call of SyncImages.
func (mr *MockSyncMockRecorder) SyncImages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncImages", reflect.TypeOf((*MockSync)(nil).SyncImages), ctx)
}

// MockRules is a mock of Rules interface.
type MockRules struct {
	ctrl     *gomock.Controller
	recorder *MockRulesMockRecorder
	isgomock struct{}
}

// MockRulesMockRecorder is the mock recorder for MockRules.
type MockRulesMockRecorder struct {
	mock *MockRules
}

// NewMockRules creates a new mock instance.
func NewMockRules(ctrl *gomock.Controller) *MockRules {
	mock := &MockRules{ctrl: ctrl}
	mock.recorder = &MockRulesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRules) EXPECT() *MockRulesMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRules) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRulesMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRules)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockRules) Create(ctx context.Context, rule entity.DeliveryRule) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRulesMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRules)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockRules) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRulesMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRules)(nil).Delete), ctx, id)
}

// FirstScheduledChannel mocks base method.
func (m *MockRules) FirstScheduledChannel(ctx context.Context) (string, int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstScheduledChannel", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FirstScheduledChannel indicates an expected call of FirstScheduledChannel.
func (mr *MockRulesMockRecorder) FirstScheduledChannel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstScheduledChannel", reflect.TypeOf((*MockRules)(nil).FirstScheduledChannel), ctx)
}

// Get mocks base method.
func (m *MockRules) Get(ctx context.Context, id int64) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRulesMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRules)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockRules) List(ctx context.Context) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRulesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRules)(nil).List), ctx)
}

// ListActiveByTrigger mocks base method.
func (m *MockRules) ListActiveByTrigger(ctx context.Context, triggerType string) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByTrigger", ctx, triggerType)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByTrigger indicates an expected call of ListActiveByTrigger.
func (mr *MockRulesMockRecorder) ListActiveByTrigger(ctx, triggerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByTrigger", reflect.TypeOf((*MockRules)(nil).ListActiveByTrigger), ctx, triggerType)
}

// Update mocks base method.
func (m *MockRules) Update(ctx context.Context, id int64, rule entity.DeliveryRule) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, rule)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRulesMockRecorder) Update(ctx, id, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRules)(nil).Update), ctx, id, rule)
}

// MockAppSettings is a mock of AppSettings interface.
type MockAppSettings struct {
	ctrl     *gomock.Controller
	recorder *MockAppSettingsMockRecorder
	isgomock struct{}
}

// MockAppSettingsMockRecorder is the mock recorder for MockAppSettings.
type MockAppSettingsMockRecorder struct {
	mock *MockAppSettings
}

// NewMockAppSettings creates a new mock instance.
func NewMockAppSettings(ctrl *gomock.Controller) *MockAppSettings {
	mock := &MockAppSettings{ctrl: ctrl}
	mock.recorder = &MockAppSettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppSettings) EXPECT() *MockAppSettingsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAppSettings) Get(ctx context.Context) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAppSettingsMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppSettings)(nil).Get), ctx)
}

// GetIngestAPIKey mocks base method.
func (m *MockAppSettings) GetIngestAPIKey(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngestAPIKey", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngestAPIKey indicates an expected call of GetIngestAPIKey.
func (mr *MockAppSettingsMockRecorder) GetIngestAPIKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngestAPIKey", reflect.TypeOf((*MockAppSettings)(nil).GetIngestAPIKey), ctx)
}

// GetSyncInterval mocks base method.
func (m *MockAppSettings) GetSyncInterval(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncInterval", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncInterval indicates an expected call of GetSyncInterval.
func (mr *MockAppSettingsMockRecorder) GetSyncInterval(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncInterval", reflect.TypeOf((*MockAppSettings)(nil).GetSyncInterval), ctx)
}

// HasIngestAPIKey mocks base method.
func (m *MockAppSettings) HasIngestAPIKey(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasIngestAPIKey", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasIngestAPIKey indicates an expected call of HasIngestAPIKey.
func (mr *MockAppSettingsMockRecorder) HasIngestAPIKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasIngestAPIKey", reflect.TypeOf((*MockAppSettings)(nil).HasIngestAPIKey), ctx)
}

// SetIngestAPIKey mocks base method.
func (m *MockAppSettings) SetIngestAPIKey(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIngestAPIKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIngestAPIKey indicates an expected call of SetIngestAPIKey.
func (mr *MockAppSettingsMockRecorder) SetIngestAPIKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIngestAPIKey", reflect.TypeOf((*MockAppSettings)(nil).SetIngestAPIKey), ctx, key)
}

// SetMessageDefaults mocks base method.
func (m *MockAppSettings) SetMessageDefaults(ctx context.Context, style entity.MessageStyle) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMessageDefaults", ctx, style)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMessageDefaults indicates an expected call of SetMessageDefaults.
func (mr *MockAppSettingsMockRecorder) SetMessageDefaults(ctx, style any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessageDefaults", reflect.TypeOf((*MockAppSettings)(nil).SetMessageDefaults), ctx, style)
}

// SetSyncInterval mocks base method.
func (m *MockAppSettings) SetSyncInterval(ctx context.Context, interval string) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSyncInterval", ctx, interval)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSyncInterval indicates an expected call of SetSyncInterval.
func (mr *MockAppSettingsMockRecorder) SetSyncInterval(ctx, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSyncInterval", reflect.TypeOf((*MockAppSettings)(nil).SetSyncInterval), ctx, interval)
}

// MockJobs is a mock of Jobs interface.
type MockJobs struct {
	ctrl     *gomock.Controller
	recorder *MockJobsMockRecorder
	isgomock struct{}
}

// MockJobsMockRecorder is the mock recorder for MockJobs.
type MockJobsMockRecorder struct {
	mock *MockJobs
}

// NewMockJobs creates a new mock instance.
func NewMockJobs(ctrl *gomock.Controller) *MockJobs {
	mock := &MockJobs{ctrl: ctrl}
	mock.recorder = &MockJobsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobs) EXPECT() *MockJobsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockJobs) List() []entity.Job {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]entity.Job)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockJobsMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockJobs)(nil).List))
}

// Start mocks base method.
func (m *MockJobs) Start(kind entity.JobKind, label string, fn func(context.Context) (map[string]any, error)) entity.Job {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", kind, label, fn)
	ret0, _ := ret[0].(entity.Job)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockJobsMockRecorder) Start(kind, label, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockJobs)(nil).Start), kind, label, fn)
}

// MockAdminRuntime is a mock of AdminRuntime interface.
type MockAdminRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRuntimeMockRecorder
	isgomock struct{}
}

// MockAdminRuntimeMockRecorder is the mock recorder for MockAdminRuntime.
type MockAdminRuntimeMockRecorder struct {
	mock *MockAdminRuntime
}

// NewMockAdminRuntime creates a new mock instance.
func NewMockAdminRuntime(ctrl *gomock.Controller) *MockAdminRuntime {
	mock := &MockAdminRuntime{ctrl: ctrl}
	mock.recorder = &MockAdminRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRuntime) EXPECT() *MockAdminRuntimeMockRecorder {
	return m.recorder
}

// GetDiscordStatus mocks base method.
func (m *MockAdminRuntime) GetDiscordStatus(ctx context.Context) (bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordStatus", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetDiscordStatus indicates an expected call of GetDiscordStatus.
func (mr *MockAdminRuntimeMockRecorder) GetDiscordStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordStatus", reflect.TypeOf((*MockAdminRuntime)(nil).GetDiscordStatus), ctx)
}

// SendAlbumTest mocks base method.
func (m *MockAdminRuntime) SendAlbumTest(ctx context.Context, channelID string, albumID int) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAlbumTest", ctx, channelID, albumID)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAlbumTest indicates an expected call of SendAlbumTest.
func (mr *MockAdminRuntimeMockRecorder) SendAlbumTest(ctx, channelID, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlbumTest", reflect.TypeOf((*MockAdminRuntime)(nil).SendAlbumTest), ctx, channelID, albumID)
}

// SendRuleTest mocks base method.
func (m *MockAdminRuntime) SendRuleTest(ctx context.Context, ruleID int64, albumID int) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRuleTest", ctx, ruleID, albumID)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRuleTest indicates an expected call of SendRuleTest.
func (mr *MockAdminRuntimeMockRecorder) SendRuleTest(ctx, ruleID, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRuleTest", reflect.TypeOf((*MockAdminRuntime)(nil).SendRuleTest), ctx, ruleID, albumID)
}

// TriggerScheduleNow mocks base method.
func (m *MockAdminRuntime) TriggerScheduleNow(ctx context.Context, channelID string, historySize int) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScheduleNow", ctx, channelID, historySize)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerScheduleNow indicates an expected call of TriggerScheduleNow.
func (mr *MockAdminRuntimeMockRecorder) TriggerScheduleNow(ctx, channelID, historySize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScheduleNow", reflect.TypeOf((*MockAdminRuntime)(nil).TriggerScheduleNow), ctx, channelID, historySize)
}

// TriggerSyncNow mocks base method.
func (m *MockAdminRuntime) TriggerSyncNow(ctx context.Context) (entity.SyncReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSyncNow", ctx)
	ret0, _ := ret[0].(entity.SyncReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerSyncNow indicates an expected call of TriggerSyncNow.
func (mr *MockAdminRuntimeMockRecorder) TriggerSyncNow(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSyncNow", reflect.TypeOf((*MockAdminRuntime)(nil).TriggerSyncNow), ctx)
}

// MockTaskRuns is a mock of TaskRuns interface.
type MockTaskRuns struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunsMockRecorder
	isgomock struct{}
}

// MockTaskRunsMockRecorder is the mock recorder for MockTaskRuns.
type MockTaskRunsMockRecorder struct {
	mock *MockTaskRuns
}

// NewMockTaskRuns creates a new mock instance.
func NewMockTaskRuns(ctrl *gomock.Controller) *MockTaskRuns {
	mock := &MockTaskRuns{ctrl: ctrl}
	mock.recorder = &MockTaskRunsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRuns) EXPECT() *MockTaskRunsMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockTaskRuns) Complete(ctx context.Context, id int64, outcome entity.TaskRun) (entity.TaskRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, id, outcome)
	ret0, _ := ret[0].(entity.TaskRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockTaskRunsMockRecorder) Complete(ctx, id, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockTaskRuns)(nil).Complete), ctx, id, outcome)
}

// Finish mocks base method.
func (m *MockTaskRuns) Finish(ctx context.Context, id int64, status, summary string, detail map[string]any, runErr error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finish", ctx, id, status, summary, detail, runErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finish indicates an expected call of Finish.
func (mr *MockTaskRunsMockRecorder) Finish(ctx, id, status, summary, detail, runErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockTaskRuns)(nil).Finish), ctx, id, status, summary, detail, runErr)
}

// List mocks base method.
func (m *MockTaskRuns) List(ctx context.Context, q repo.TaskRunListQuery, offset, limit int) ([]entity.TaskRun, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.TaskRun)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRunsMockRecorder) List(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRuns)(nil).List), ctx, q, offset, limit)
}

// Prune mocks base method.
func (m *MockTaskRuns) Prune(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockTaskRunsMockRecorder) Prune(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockTaskRuns)(nil).Prune), ctx)
}

// Record mocks base method.
func (m *MockTaskRuns) Record(ctx context.Context, run entity.TaskRun) (entity.TaskRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, run)
	ret0, _ := ret[0].(entity.TaskRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Record indicates an expected call of Record.
func (mr *MockTaskRunsMockRecorder) Record(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockTaskRuns)(nil).Record), ctx, run)
}

// Sources mocks base method.
func (m *MockTaskRuns) Sources(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sources", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sources indicates an expected call of Sources.
func (mr *MockTaskRunsMockRecorder) Sources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sources", reflect.TypeOf((*MockTaskRuns)(nil).Sources), ctx)
}

// Started mocks base method.
func (m *MockTaskRuns) Started(ctx context.Context, source, task string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Started", ctx, source, task)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Started indicates an expected call of Started.
func (mr *MockTaskRunsMockRecorder) Started(ctx, source, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Started", reflect.TypeOf((*MockTaskRuns)(nil).Started), ctx, source, task)
}

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// CreateAlbum mocks base method.
func (m *MockAdmin) CreateAlbum(ctx context.Context, name string, sendMode entity.AlbumSendMode, sendConfigJSON string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlbum", ctx, name, sendMode, sendConfigJSON)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlbum indicates an expected call of CreateAlbum.
func (mr *MockAdminMockRecorder) CreateAlbum(ctx, name, sendMode, sendConfigJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlbum", reflect.TypeOf((*MockAdmin)(nil).CreateAlbum), ctx, name, sendMode, sendConfigJSON)
}

// CreateImage mocks base method.
func (m *MockAdmin) CreateImage(ctx context.Context, img entity.Image) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImage", ctx, img)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImage indicates an expected call of CreateImage.
func (mr *MockAdminMockRecorder) CreateImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImage", reflect.TypeOf((*MockAdmin)(nil).CreateImage), ctx, img)
}

// CreateRule mocks base method.
func (m *MockAdmin) CreateRule(ctx context.Context, rule entity.DeliveryRule, actor string) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, rule, actor)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockAdminMockRecorder) CreateRule(ctx, rule, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockAdmin)(nil).CreateRule), ctx, rule, actor)
}

// DeleteAlbum mocks base method.
func (m *MockAdmin) DeleteAlbum(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlbum", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlbum indicates an expected call of DeleteAlbum.
func (mr *MockAdminMockRecorder) DeleteAlbum(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlbum", reflect.TypeOf((*MockAdmin)(nil).DeleteAlbum), ctx, id)
}

// DeleteImage mocks base method.
func (m *MockAdmin) DeleteImage(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockAdminMockRecorder) DeleteImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockAdmin)(nil).DeleteImage), ctx, id)
}

// DeleteRule mocks base method.
func (m *MockAdmin) DeleteRule(ctx context.Context, id int64, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockAdminMockRecorder) DeleteRule(ctx, id, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockAdmin)(nil).DeleteRule), ctx, id, actor)
}

// GetAlbum mocks base method.
func (m *MockAdmin) GetAlbum(ctx context.Context, id int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbum", ctx, id)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbum indicates an expected call of GetAlbum.
func (mr *MockAdminMockRecorder) GetAlbum(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbum", reflect.TypeOf((*MockAdmin)(nil).GetAlbum), ctx, id)
}

// GetImage mocks base method.
func (m *MockAdmin) GetImage(ctx context.Context, id int) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockAdminMockRecorder) GetImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockAdmin)(nil).GetImage), ctx, id)
}

// GetRule mocks base method.
func (m *MockAdmin) GetRule(ctx context.Context, id int64) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockAdminMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockAdmin)(nil).GetRule), ctx, id)
}

// GetSyncSettings mocks base method.
func (m *MockAdmin) GetSyncSettings(ctx context.Context) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncSettings", ctx)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncSettings indicates an expected call of GetSyncSettings.
func (mr *MockAdminMockRecorder) GetSyncSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncSettings", reflect.TypeOf((*MockAdmin)(nil).GetSyncSettings), ctx)
}

// GetSystemStatus mocks base method.
func (m *MockAdmin) GetSystemStatus(ctx context.Context) (entity.SystemStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStatus", ctx)
	ret0, _ := ret[0].(entity.SystemStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStatus indicates an expected call of GetSystemStatus.
func (mr *MockAdminMockRecorder) GetSystemStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStatus", reflect.TypeOf((*MockAdmin)(nil).GetSystemStatus), ctx)
}

// HasIngestAPIKey mocks base method.
func (m *MockAdmin) HasIngestAPIKey(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasIngestAPIKey", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasIngestAPIKey indicates an expected call of HasIngestAPIKey.
func (mr *MockAdminMockRecorder) HasIngestAPIKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasIngestAPIKey", reflect.TypeOf((*MockAdmin)(nil).HasIngestAPIKey), ctx)
}

// ListAlbumMedia mocks base method.
func (m *MockAdmin) ListAlbumMedia(ctx context.Context, albumID, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlbumMedia", ctx, albumID, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlbumMedia indicates an expected call of ListAlbumMedia.
func (mr *MockAdminMockRecorder) ListAlbumMedia(ctx, albumID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlbumMedia", reflect.TypeOf((*MockAdmin)(nil).ListAlbumMedia), ctx, albumID, limit)
}

// ListAlbums mocks base method.
func (m *MockAdmin) ListAlbums(ctx context.Context, q repo.AlbumAdminListQuery, offset, limit int) ([]entity.Album, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlbums", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.Album)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAlbums indicates an expected call of ListAlbums.
func (mr *MockAdminMockRecorder) ListAlbums(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlbums", reflect.TypeOf((*MockAdmin)(nil).ListAlbums), ctx, q, offset, limit)
}

// ListImages mocks base method.
func (m *MockAdmin) ListImages(ctx context.Context, q repo.ImageAdminListQuery, offset, limit int) ([]entity.Image, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListImages indicates an expected call of ListImages.
func (mr *MockAdminMockRecorder) ListImages(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockAdmin)(nil).ListImages), ctx, q, offset, limit)
}

// ListJobs mocks base method.
func (m *MockAdmin) ListJobs(ctx context.Context) []entity.Job {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", ctx)
	ret0, _ := ret[0].([]entity.Job)
	return ret0
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockAdminMockRecorder) ListJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockAdmin)(nil).ListJobs), ctx)
}

// ListRules mocks base method.
func (m *MockAdmin) ListRules(ctx context.Context) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockAdminMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockAdmin)(nil).ListRules), ctx)
}

// ListSyncEventMedia mocks base method.
func (m *MockAdmin) ListSyncEventMedia(ctx context.Context, eventID int64) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncEventMedia", ctx, eventID)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSyncEventMedia indicates an expected call of ListSyncEventMedia.
func (mr *MockAdminMockRecorder) ListSyncEventMedia(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncEventMedia", reflect.TypeOf((*MockAdmin)(nil).ListSyncEventMedia), ctx, eventID)
}

// ListSyncEvents mocks base method.
func (m *MockAdmin) ListSyncEvents(ctx context.Context, offset, limit int) ([]entity.SyncEvent, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncEvents", ctx, offset, limit)
	ret0, _ := ret[0].([]entity.SyncEvent)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSyncEvents indicates an expected call of ListSyncEvents.
func (mr *MockAdminMockRecorder) ListSyncEvents(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncEvents", reflect.TypeOf((*MockAdmin)(nil).ListSyncEvents), ctx, offset, limit)
}

// ListTaskRunSources mocks base method.
func (m *MockAdmin) ListTaskRunSources(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskRunSources", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskRunSources indicates an expected call of ListTaskRunSources.
func (mr *MockAdminMockRecorder) ListTaskRunSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskRunSources", reflect.TypeOf((*MockAdmin)(nil).ListTaskRunSources), ctx)
}

// ListTaskRuns mocks base method.
func (m *MockAdmin) ListTaskRuns(ctx context.Context, q repo.TaskRunListQuery, offset, limit int) ([]entity.TaskRun, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskRuns", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.TaskRun)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTaskRuns indicates an expected call of ListTaskRuns.
func (mr *MockAdminMockRecorder) ListTaskRuns(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskRuns", reflect.TypeOf((*MockAdmin)(nil).ListTaskRuns), ctx, q, offset, limit)
}

// RecordAudit mocks base method.
func (m *MockAdmin) RecordAudit(ctx context.Context, actor, action, targetType, targetID string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAudit", ctx, actor, action, targetType, targetID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAudit indicates an expected call of RecordAudit.
func (mr *MockAdminMockRecorder) RecordAudit(ctx, actor, action, targetType, targetID, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAudit", reflect.TypeOf((*MockAdmin)(nil).RecordAudit), ctx, actor, action, targetType, targetID, metadata)
}

// SendAlbumTest mocks base method.
func (m *MockAdmin) SendAlbumTest(ctx context.Context, albumID int, channelID, actor string) (entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAlbumTest", ctx, albumID, channelID, actor)
	ret0, _ := ret[0].(entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAlbumTest indicates an expected call of SendAlbumTest.
func (mr *MockAdminMockRecorder) SendAlbumTest(ctx, albumID, channelID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlbumTest", reflect.TypeOf((*MockAdmin)(nil).SendAlbumTest), ctx, albumID, channelID, actor)
}

// SetIngestAPIKey mocks base method.
func (m *MockAdmin) SetIngestAPIKey(ctx context.Context, key, actor string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIngestAPIKey", ctx, key, actor)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIngestAPIKey indicates an expected call of SetIngestAPIKey.
func (mr *MockAdminMockRecorder) SetIngestAPIKey(ctx, key, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIngestAPIKey", reflect.TypeOf((*MockAdmin)(nil).SetIngestAPIKey), ctx, key, actor)
}

// TestRule mocks base method.
func (m *MockAdmin) TestRule(ctx context.Context, ruleID int64, albumID int, actor string) (entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestRule", ctx, ruleID, albumID, actor)
	ret0, _ := ret[0].(entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestRule indicates an expected call of TestRule.
func (mr *MockAdminMockRecorder) TestRule(ctx, ruleID, albumID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestRule", reflect.TypeOf((*MockAdmin)(nil).TestRule), ctx, ruleID, albumID, actor)
}

// TriggerScheduleNow mocks base method.
func (m *MockAdmin) TriggerScheduleNow(ctx context.Context, channelID, actor string) (entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScheduleNow", ctx, channelID, actor)
	ret0, _ := ret[0].(entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerScheduleNow indicates an expected call of TriggerScheduleNow.
func (mr *MockAdminMockRecorder) TriggerScheduleNow(ctx, channelID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScheduleNow", reflect.TypeOf((*MockAdmin)(nil).TriggerScheduleNow), ctx, channelID, actor)
}

// TriggerSyncNow mocks base method.
func (m *MockAdmin) TriggerSyncNow(ctx context.Context, actor string) (entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSyncNow", ctx, actor)
	ret0, _ := ret[0].(entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerSyncNow indicates an expected call of TriggerSyncNow.
func (mr *MockAdminMockRecorder) TriggerSyncNow(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSyncNow", reflect.TypeOf((*MockAdmin)(nil).TriggerSyncNow), ctx, actor)
}

// UpdateAlbum mocks base method.
func (m *MockAdmin) UpdateAlbum(ctx context.Context, id int, name string, sendMode entity.AlbumSendMode, sendConfigJSON string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlbum", ctx, id, name, sendMode, sendConfigJSON)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAlbum indicates an expected call of UpdateAlbum.
func (mr *MockAdminMockRecorder) UpdateAlbum(ctx, id, name, sendMode, sendConfigJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlbum", reflect.TypeOf((*MockAdmin)(nil).UpdateAlbum), ctx, id, name, sendMode, sendConfigJSON)
}

// UpdateImage mocks base method.
func (m *MockAdmin) UpdateImage(ctx context.Context, img entity.Image) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", ctx, img)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockAdminMockRecorder) UpdateImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockAdmin)(nil).UpdateImage), ctx, img)
}

// UpdateMessageDefaults mocks base method.
func (m *MockAdmin) UpdateMessageDefaults(ctx context.Context, style entity.MessageStyle, actor string) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageDefaults", ctx, style, actor)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessageDefaults indicates an expected call of UpdateMessageDefaults.
func (mr *MockAdminMockRecorder) UpdateMessageDefaults(ctx, style, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageDefaults", reflect.TypeOf((*MockAdmin)(nil).UpdateMessageDefaults), ctx, style, actor)
}

// UpdateRule mocks base method.
func (m *MockAdmin) UpdateRule(ctx context.Context, id int64, rule entity.DeliveryRule, actor string) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, id, rule, actor)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockAdminMockRecorder) UpdateRule(ctx, id, rule, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockAdmin)(nil).UpdateRule), ctx, id, rule, actor)
}

// UpdateSyncSettings mocks base method.
func (m *MockAdmin) UpdateSyncSettings(ctx context.Context, interval, actor string) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncSettings", ctx, interval, actor)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSyncSettings indicates an expected call of UpdateSyncSettings.
func (mr *MockAdminMockRecorder) UpdateSyncSettings(ctx, interval, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncSettings", reflect.TypeOf((*MockAdmin)(nil).UpdateSyncSettings), ctx, interval, actor)
}
