// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/AaronCheng1996/sendmemes-discord-bot/internal/entity"
	repo "github.com/AaronCheng1996/sendmemes-discord-bot/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslation is a mock of Translation interface.
type MockTranslation struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationMockRecorder
	isgomock struct{}
}

// MockTranslationMockRecorder is the mock recorder for MockTranslation.
type MockTranslationMockRecorder struct {
	mock *MockTranslation
}

// NewMockTranslation creates a new mock instance.
func NewMockTranslation(ctrl *gomock.Controller) *MockTranslation {
	mock := &MockTranslation{ctrl: ctrl}
	mock.recorder = &MockTranslationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslation) EXPECT() *MockTranslationMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockTranslation) History(arg0 context.Context) (entity.TranslationHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", arg0)
	ret0, _ := ret[0].(entity.TranslationHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockTranslationMockRecorder) History(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockTranslation)(nil).History), arg0)
}

// Translate mocks base method.
func (m *MockTranslation) Translate(arg0 context.Context, arg1 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0, arg1)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationMockRecorder) Translate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslation)(nil).Translate), arg0, arg1)
}

// MockImages is a mock of Images interface.
type MockImages struct {
	ctrl     *gomock.Controller
	recorder *MockImagesMockRecorder
	isgomock struct{}
}

// MockImagesMockRecorder is the mock recorder for MockImages.
type MockImagesMockRecorder struct {
	mock *MockImages
}

// NewMockImages creates a new mock instance.
func NewMockImages(ctrl *gomock.Controller) *MockImages {
	mock := &MockImages{ctrl: ctrl}
	mock.recorder = &MockImagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImages) EXPECT() *MockImagesMockRecorder {
	return m.recorder
}

// GetAlbumBatch mocks base method.
func (m *MockImages) GetAlbumBatch(ctx context.Context, album entity.Album, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumBatch", ctx, album, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumBatch indicates an expected call of GetAlbumBatch.
func (mr *MockImagesMockRecorder) GetAlbumBatch(ctx, album, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumBatch", reflect.TypeOf((*MockImages)(nil).GetAlbumBatch), ctx, album, limit)
}

// GetAlbumByID mocks base method.
func (m *MockImages) GetAlbumByID(ctx context.Context, id int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumByID", ctx, id)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByID indicates an expected call of GetAlbumByID.
func (mr *MockImagesMockRecorder) GetAlbumByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByID", reflect.TypeOf((*MockImages)(nil).GetAlbumByID), ctx, id)
}

// GetAlbumCover mocks base method.
func (m *MockImages) GetAlbumCover(ctx context.Context, albumName string) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumCover", ctx, albumName)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAlbumCover indicates an expected call of GetAlbumCover.
func (mr *MockImagesMockRecorder) GetAlbumCover(ctx, albumName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumCover", reflect.TypeOf((*MockImages)(nil).GetAlbumCover), ctx, albumName)
}

// GetAlbumImages mocks base method.
func (m *MockImages) GetAlbumImages(ctx context.Context, albumName string, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumImages", ctx, albumName, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumImages indicates an expected call of GetAlbumImages.
func (mr *MockImagesMockRecorder) GetAlbumImages(ctx, albumName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumImages", reflect.TypeOf((*MockImages)(nil).GetAlbumImages), ctx, albumName, limit)
}

// GetComicPages mocks base method.
func (m *MockImages) GetComicPages(ctx context.Context, album entity.Album) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicPages", ctx, album)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicPages indicates an expected call of GetComicPages.
func (mr *MockImagesMockRecorder) GetComicPages(ctx, album any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicPages", reflect.TypeOf((*MockImages)(nil).GetComicPages), ctx, album)
}

// GetFullAlbum mocks base method.
func (m *MockImages) GetFullAlbum(ctx context.Context, albumName string) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullAlbum", ctx, albumName)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullAlbum indicates an expected call of GetFullAlbum.
func (mr *MockImagesMockRecorder) GetFullAlbum(ctx, albumName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullAlbum", reflect.TypeOf((*MockImages)(nil).GetFullAlbum), ctx, albumName)
}

// GetImage mocks base method.
func (m *MockImages) GetImage(ctx context.Context) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockImagesMockRecorder) GetImage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockImages)(nil).GetImage), ctx)
}

// GetRandom mocks base method.
func (m *MockImages) GetRandom(ctx context.Context) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom", ctx)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockImagesMockRecorder) GetRandom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockImages)(nil).GetRandom), ctx)
}

// GetRandomAlbumImages mocks base method.
func (m *MockImages) GetRandomAlbumImages(ctx context.Context, limit int) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomAlbumImages", ctx, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomAlbumImages indicates an expected call of GetRandomAlbumImages.
func (mr *MockImagesMockRecorder) GetRandomAlbumImages(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomAlbumImages", reflect.TypeOf((*MockImages)(nil).GetRandomAlbumImages), ctx, limit)
}

// GetRandomVideo mocks base method.
func (m *MockImages) GetRandomVideo(ctx context.Context, albumID int) (entity.Image, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomVideo", ctx, albumID)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRandomVideo indicates an expected call of GetRandomVideo.
func (mr *MockImagesMockRecorder) GetRandomVideo(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomVideo", reflect.TypeOf((*MockImages)(nil).GetRandomVideo), ctx, albumID)
}

// GetScheduledAlbum mocks base method.
func (m *MockImages) GetScheduledAlbum(ctx context.Context, excludeN int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledAlbum", ctx, excludeN)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledAlbum indicates an expected call of GetScheduledAlbum.
func (mr *MockImagesMockRecorder) GetScheduledAlbum(ctx, excludeN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledAlbum", reflect.TypeOf((*MockImages)(nil).GetScheduledAlbum), ctx, excludeN)
}

// IncrAlbumRating mocks base method.
func (m *MockImages) IncrAlbumRating(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrAlbumRating", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrAlbumRating indicates an expected call of IncrAlbumRating.
func (mr *MockImagesMockRecorder) IncrAlbumRating(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrAlbumRating", reflect.TypeOf((*MockImages)(nil).IncrAlbumRating), ctx, albumID)
}

// MarkAlbumSent mocks base method.
func (m *MockImages) MarkAlbumSent(ctx context.Context, albumID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAlbumSent", ctx, albumID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAlbumSent indicates an expected call of MarkAlbumSent.
func (mr *MockImagesMockRecorder) MarkAlbumSent(ctx, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAlbumSent", reflect.TypeOf((*MockImages)(nil).MarkAlbumSent), ctx, albumID)
}

// ResolveURL mocks base method.
func (m *MockImages) ResolveURL(ctx context.Context, img entity.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveURL", ctx, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveURL indicates an expected call of ResolveURL.
func (mr *MockImagesMockRecorder) ResolveURL(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveURL", reflect.TypeOf((*MockImages)(nil).ResolveURL), ctx, img)
}

// SetAlbumMode mocks base method.
func (m *MockImages) SetAlbumMode(ctx context.Context, albumName string, mode entity.AlbumSendMode) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAlbumMode", ctx, albumName, mode)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAlbumMode indicates an expected call of SetAlbumMode.
func (mr *MockImagesMockRecorder) SetAlbumMode(ctx, albumName, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAlbumMode", reflect.TypeOf((*MockImages)(nil).SetAlbumMode), ctx, albumName, mode)
}

// MockSync is a mock of Sync interface.
type MockSync struct {
	ctrl     *gomock.Controller
	recorder *MockSyncMockRecorder
	isgomock struct{}
}

// MockSyncMockRecorder is the mock recorder for MockSync.
type MockSyncMockRecorder struct {
	mock *MockSync
}

// NewMockSync creates a new mock instance.
func NewMockSync(ctrl *gomock.Controller) *MockSync {
	mock := &MockSync{ctrl: ctrl}
	mock.recorder = &MockSyncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSync) EXPECT() *MockSyncMockRecorder {
	return m.recorder
}

// SyncImages mocks base method.
func (m *MockSync) SyncImages(ctx context.Context) (entity.SyncReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncImages", ctx)
	ret0, _ := ret[0].(entity.SyncReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncImages indicates an expected call of SyncImages.
func (mr *MockSyncMockRecorder) SyncImages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncImages", reflect.TypeOf((*MockSync)(nil).SyncImages), ctx)
}

// MockRules is a mock of Rules interface.
type MockRules struct {
	ctrl     *gomock.Controller
	recorder *MockRulesMockRecorder
	isgomock struct{}
}

// MockRulesMockRecorder is the mock recorder for MockRules.
type MockRulesMockRecorder struct {
	mock *MockRules
}

// NewMockRules creates a new mock instance.
func NewMockRules(ctrl *gomock.Controller) *MockRules {
	mock := &MockRules{ctrl: ctrl}
	mock.recorder = &MockRulesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRules) EXPECT() *MockRulesMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRules) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRulesMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRules)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockRules) Create(ctx context.Context, rule entity.DeliveryRule) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRulesMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRules)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockRules) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRulesMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRules)(nil).Delete), ctx, id)
}

// FirstScheduledChannel mocks base method.
func (m *MockRules) FirstScheduledChannel(ctx context.Context) (string, int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstScheduledChannel", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FirstScheduledChannel indicates an expected call of FirstScheduledChannel.
func (mr *MockRulesMockRecorder) FirstScheduledChannel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstScheduledChannel", reflect.TypeOf((*MockRules)(nil).FirstScheduledChannel), ctx)
}

// Get mocks base method.
func (m *MockRules) Get(ctx context.Context, id int64) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRulesMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRules)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockRules) List(ctx context.Context) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRulesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRules)(nil).List), ctx)
}

// ListActiveByTrigger mocks base method.
func (m *MockRules) ListActiveByTrigger(ctx context.Context, triggerType string) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByTrigger", ctx, triggerType)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByTrigger indicates an expected call of ListActiveByTrigger.
func (mr *MockRulesMockRecorder) ListActiveByTrigger(ctx, triggerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByTrigger", reflect.TypeOf((*MockRules)(nil).ListActiveByTrigger), ctx, triggerType)
}

// Update mocks base method.
func (m *MockRules) Update(ctx context.Context, id int64, rule entity.DeliveryRule) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, rule)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRulesMockRecorder) Update(ctx, id, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRules)(nil).Update), ctx, id, rule)
}

// MockAppSettings is a mock of AppSettings interface.
type MockAppSettings struct {
	ctrl     *gomock.Controller
	recorder *MockAppSettingsMockRecorder
	isgomock struct{}
}

// MockAppSettingsMockRecorder is the mock recorder for MockAppSettings.
type MockAppSettingsMockRecorder struct {
	mock *MockAppSettings
}

// NewMockAppSettings creates a new mock instance.
func NewMockAppSettings(ctrl *gomock.Controller) *MockAppSettings {
	mock := &MockAppSettings{ctrl: ctrl}
	mock.recorder = &MockAppSettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppSettings) EXPECT() *MockAppSettingsMockRecorder {
	return m.recorder
}

// GetSyncInterval mocks base method.
func (m *MockAppSettings) GetSyncInterval(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncInterval", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncInterval indicates an expected call of GetSyncInterval.
func (mr *MockAppSettingsMockRecorder) GetSyncInterval(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncInterval", reflect.TypeOf((*MockAppSettings)(nil).GetSyncInterval), ctx)
}

// SetSyncInterval mocks base method.
func (m *MockAppSettings) SetSyncInterval(ctx context.Context, interval string) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSyncInterval", ctx, interval)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSyncInterval indicates an expected call of SetSyncInterval.
func (mr *MockAppSettingsMockRecorder) SetSyncInterval(ctx, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSyncInterval", reflect.TypeOf((*MockAppSettings)(nil).SetSyncInterval), ctx, interval)
}

// MockAdminRuntime is a mock of AdminRuntime interface.
type MockAdminRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRuntimeMockRecorder
	isgomock struct{}
}

// MockAdminRuntimeMockRecorder is the mock recorder for MockAdminRuntime.
type MockAdminRuntimeMockRecorder struct {
	mock *MockAdminRuntime
}

// NewMockAdminRuntime creates a new mock instance.
func NewMockAdminRuntime(ctrl *gomock.Controller) *MockAdminRuntime {
	mock := &MockAdminRuntime{ctrl: ctrl}
	mock.recorder = &MockAdminRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRuntime) EXPECT() *MockAdminRuntimeMockRecorder {
	return m.recorder
}

// GetDiscordStatus mocks base method.
func (m *MockAdminRuntime) GetDiscordStatus(ctx context.Context) (bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordStatus", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetDiscordStatus indicates an expected call of GetDiscordStatus.
func (mr *MockAdminRuntimeMockRecorder) GetDiscordStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordStatus", reflect.TypeOf((*MockAdminRuntime)(nil).GetDiscordStatus), ctx)
}

// SendAlbumTest mocks base method.
func (m *MockAdminRuntime) SendAlbumTest(ctx context.Context, channelID string, albumID int) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAlbumTest", ctx, channelID, albumID)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAlbumTest indicates an expected call of SendAlbumTest.
func (mr *MockAdminRuntimeMockRecorder) SendAlbumTest(ctx, channelID, albumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlbumTest", reflect.TypeOf((*MockAdminRuntime)(nil).SendAlbumTest), ctx, channelID, albumID)
}

// TriggerScheduleNow mocks base method.
func (m *MockAdminRuntime) TriggerScheduleNow(ctx context.Context, channelID string, historySize int) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScheduleNow", ctx, channelID, historySize)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerScheduleNow indicates an expected call of TriggerScheduleNow.
func (mr *MockAdminRuntimeMockRecorder) TriggerScheduleNow(ctx, channelID, historySize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScheduleNow", reflect.TypeOf((*MockAdminRuntime)(nil).TriggerScheduleNow), ctx, channelID, historySize)
}

// TriggerSyncNow mocks base method.
func (m *MockAdminRuntime) TriggerSyncNow(ctx context.Context) (entity.SyncReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSyncNow", ctx)
	ret0, _ := ret[0].(entity.SyncReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerSyncNow indicates an expected call of TriggerSyncNow.
func (mr *MockAdminRuntimeMockRecorder) TriggerSyncNow(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSyncNow", reflect.TypeOf((*MockAdminRuntime)(nil).TriggerSyncNow), ctx)
}

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// CreateAlbum mocks base method.
func (m *MockAdmin) CreateAlbum(ctx context.Context, name string, sendMode entity.AlbumSendMode, sendConfigJSON string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlbum", ctx, name, sendMode, sendConfigJSON)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlbum indicates an expected call of CreateAlbum.
func (mr *MockAdminMockRecorder) CreateAlbum(ctx, name, sendMode, sendConfigJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlbum", reflect.TypeOf((*MockAdmin)(nil).CreateAlbum), ctx, name, sendMode, sendConfigJSON)
}

// CreateImage mocks base method.
func (m *MockAdmin) CreateImage(ctx context.Context, img entity.Image) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImage", ctx, img)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImage indicates an expected call of CreateImage.
func (mr *MockAdminMockRecorder) CreateImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImage", reflect.TypeOf((*MockAdmin)(nil).CreateImage), ctx, img)
}

// CreateRule mocks base method.
func (m *MockAdmin) CreateRule(ctx context.Context, rule entity.DeliveryRule, actor string) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, rule, actor)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockAdminMockRecorder) CreateRule(ctx, rule, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockAdmin)(nil).CreateRule), ctx, rule, actor)
}

// DeleteAlbum mocks base method.
func (m *MockAdmin) DeleteAlbum(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlbum", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlbum indicates an expected call of DeleteAlbum.
func (mr *MockAdminMockRecorder) DeleteAlbum(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlbum", reflect.TypeOf((*MockAdmin)(nil).DeleteAlbum), ctx, id)
}

// DeleteImage mocks base method.
func (m *MockAdmin) DeleteImage(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockAdminMockRecorder) DeleteImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockAdmin)(nil).DeleteImage), ctx, id)
}

// DeleteRule mocks base method.
func (m *MockAdmin) DeleteRule(ctx context.Context, id int64, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockAdminMockRecorder) DeleteRule(ctx, id, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockAdmin)(nil).DeleteRule), ctx, id, actor)
}

// GetAlbum mocks base method.
func (m *MockAdmin) GetAlbum(ctx context.Context, id int) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbum", ctx, id)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbum indicates an expected call of GetAlbum.
func (mr *MockAdminMockRecorder) GetAlbum(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbum", reflect.TypeOf((*MockAdmin)(nil).GetAlbum), ctx, id)
}

// GetImage mocks base method.
func (m *MockAdmin) GetImage(ctx context.Context, id int) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockAdminMockRecorder) GetImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockAdmin)(nil).GetImage), ctx, id)
}

// GetRule mocks base method.
func (m *MockAdmin) GetRule(ctx context.Context, id int64) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockAdminMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockAdmin)(nil).GetRule), ctx, id)
}

// GetSyncSettings mocks base method.
func (m *MockAdmin) GetSyncSettings(ctx context.Context) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncSettings", ctx)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncSettings indicates an expected call of GetSyncSettings.
func (mr *MockAdminMockRecorder) GetSyncSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncSettings", reflect.TypeOf((*MockAdmin)(nil).GetSyncSettings), ctx)
}

// GetSystemStatus mocks base method.
func (m *MockAdmin) GetSystemStatus(ctx context.Context) (entity.SystemStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStatus", ctx)
	ret0, _ := ret[0].(entity.SystemStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStatus indicates an expected call of GetSystemStatus.
func (mr *MockAdminMockRecorder) GetSystemStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStatus", reflect.TypeOf((*MockAdmin)(nil).GetSystemStatus), ctx)
}

// ListAlbums mocks base method.
func (m *MockAdmin) ListAlbums(ctx context.Context, q repo.AlbumAdminListQuery, offset, limit int) ([]entity.Album, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlbums", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.Album)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAlbums indicates an expected call of ListAlbums.
func (mr *MockAdminMockRecorder) ListAlbums(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlbums", reflect.TypeOf((*MockAdmin)(nil).ListAlbums), ctx, q, offset, limit)
}

// ListImages mocks base method.
func (m *MockAdmin) ListImages(ctx context.Context, q repo.ImageAdminListQuery, offset, limit int) ([]entity.Image, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", ctx, q, offset, limit)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListImages indicates an expected call of ListImages.
func (mr *MockAdminMockRecorder) ListImages(ctx, q, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockAdmin)(nil).ListImages), ctx, q, offset, limit)
}

// ListRules mocks base method.
func (m *MockAdmin) ListRules(ctx context.Context) ([]entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockAdminMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockAdmin)(nil).ListRules), ctx)
}

// ListSyncEvents mocks base method.
func (m *MockAdmin) ListSyncEvents(ctx context.Context, offset, limit int) ([]entity.SyncEvent, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncEvents", ctx, offset, limit)
	ret0, _ := ret[0].([]entity.SyncEvent)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSyncEvents indicates an expected call of ListSyncEvents.
func (mr *MockAdminMockRecorder) ListSyncEvents(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncEvents", reflect.TypeOf((*MockAdmin)(nil).ListSyncEvents), ctx, offset, limit)
}

// RecordAudit mocks base method.
func (m *MockAdmin) RecordAudit(ctx context.Context, actor, action, targetType, targetID string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAudit", ctx, actor, action, targetType, targetID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAudit indicates an expected call of RecordAudit.
func (mr *MockAdminMockRecorder) RecordAudit(ctx, actor, action, targetType, targetID, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAudit", reflect.TypeOf((*MockAdmin)(nil).RecordAudit), ctx, actor, action, targetType, targetID, metadata)
}

// SendAlbumTest mocks base method.
func (m *MockAdmin) SendAlbumTest(ctx context.Context, albumID int, channelID, actor string) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAlbumTest", ctx, albumID, channelID, actor)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAlbumTest indicates an expected call of SendAlbumTest.
func (mr *MockAdminMockRecorder) SendAlbumTest(ctx, albumID, channelID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlbumTest", reflect.TypeOf((*MockAdmin)(nil).SendAlbumTest), ctx, albumID, channelID, actor)
}

// TriggerScheduleNow mocks base method.
func (m *MockAdmin) TriggerScheduleNow(ctx context.Context, channelID, actor string) (entity.ManualScheduleTriggerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerScheduleNow", ctx, channelID, actor)
	ret0, _ := ret[0].(entity.ManualScheduleTriggerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerScheduleNow indicates an expected call of TriggerScheduleNow.
func (mr *MockAdminMockRecorder) TriggerScheduleNow(ctx, channelID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerScheduleNow", reflect.TypeOf((*MockAdmin)(nil).TriggerScheduleNow), ctx, channelID, actor)
}

// TriggerSyncNow mocks base method.
func (m *MockAdmin) TriggerSyncNow(ctx context.Context, actor string) (entity.SyncReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSyncNow", ctx, actor)
	ret0, _ := ret[0].(entity.SyncReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerSyncNow indicates an expected call of TriggerSyncNow.
func (mr *MockAdminMockRecorder) TriggerSyncNow(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSyncNow", reflect.TypeOf((*MockAdmin)(nil).TriggerSyncNow), ctx, actor)
}

// UpdateAlbum mocks base method.
func (m *MockAdmin) UpdateAlbum(ctx context.Context, id int, name string, sendMode entity.AlbumSendMode, sendConfigJSON string) (entity.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlbum", ctx, id, name, sendMode, sendConfigJSON)
	ret0, _ := ret[0].(entity.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAlbum indicates an expected call of UpdateAlbum.
func (mr *MockAdminMockRecorder) UpdateAlbum(ctx, id, name, sendMode, sendConfigJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlbum", reflect.TypeOf((*MockAdmin)(nil).UpdateAlbum), ctx, id, name, sendMode, sendConfigJSON)
}

// UpdateImage mocks base method.
func (m *MockAdmin) UpdateImage(ctx context.Context, img entity.Image) (entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", ctx, img)
	ret0, _ := ret[0].(entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockAdminMockRecorder) UpdateImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockAdmin)(nil).UpdateImage), ctx, img)
}

// UpdateRule mocks base method.
func (m *MockAdmin) UpdateRule(ctx context.Context, id int64, rule entity.DeliveryRule, actor string) (entity.DeliveryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, id, rule, actor)
	ret0, _ := ret[0].(entity.DeliveryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockAdminMockRecorder) UpdateRule(ctx, id, rule, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockAdmin)(nil).UpdateRule), ctx, id, rule, actor)
}

// UpdateSyncSettings mocks base method.
func (m *MockAdmin) UpdateSyncSettings(ctx context.Context, interval, actor string) (entity.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncSettings", ctx, interval, actor)
	ret0, _ := ret[0].(entity.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSyncSettings indicates an expected call of UpdateSyncSettings.
func (mr *MockAdminMockRecorder) UpdateSyncSettings(ctx, interval, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncSettings", reflect.TypeOf((*MockAdmin)(nil).UpdateSyncSettings), ctx, interval, actor)
}
